/camera:
  ros__parameters:
    camera:
      device: "/dev/video0"
      format: "MPEG"
      fps: 30
      frame:
        width: 1280
        height: 720
      rotate:
        left: true
        right: false
